#!/bin/bash
#
# LINBO Docker - Machine Account Worker Installation
#
# This script installs the macct-worker on an AD DC (linuxmuster.net server)
#
# Usage:
#   sudo ./install.sh [LINBO_DOCKER_IP]
#
# Example:
#   sudo ./install.sh 10.0.0.1
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINBO_DOCKER_IP="${1:-10.0.0.1}"

echo "=========================================="
echo "LINBO Docker - macct-worker Installation"
echo "=========================================="
echo ""
echo "LINBO Docker IP: $LINBO_DOCKER_IP"
echo ""

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "Error: This script must be run as root"
   exit 1
fi

# Check if this is a linuxmuster.net server
if [[ ! -f /etc/linuxmuster/linbo/ssh_host_rsa_key ]]; then
    echo "Warning: This doesn't appear to be a linuxmuster.net server"
    read -p "Continue anyway? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Install Python dependencies
echo "Installing Python dependencies..."
apt-get update -qq
apt-get install -y python3-pip python3-redis python3-requests

# Alternative: install via pip if packages not available
pip3 install redis requests 2>/dev/null || true

# Create log directory
echo "Creating log directory..."
mkdir -p /var/log/macct
chmod 755 /var/log/macct

# Copy worker script
echo "Installing worker script..."
cp "$SCRIPT_DIR/macct-worker.py" /usr/local/bin/macct-worker.py
chmod 755 /usr/local/bin/macct-worker.py

# Create configuration
echo "Creating configuration..."
if [[ ! -f /etc/macct-worker.conf ]]; then
    cat > /etc/macct-worker.conf << EOF
# LINBO Docker Machine Account Worker Configuration
# Generated by install.sh on $(date)

# Redis connection
REDIS_HOST=$LINBO_DOCKER_IP
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

# LINBO API connection
API_URL=http://$LINBO_DOCKER_IP:3000/api/v1
API_KEY=linbo-internal-secret

# Consumer identification
CONSUMER_NAME=$(hostname)

# Log directory
LOG_DIR=/var/log/macct

# Path to repair_macct.py script
REPAIR_SCRIPT=/usr/share/linuxmuster/linbo/repair_macct.py
EOF
    chmod 600 /etc/macct-worker.conf
    echo "  Created /etc/macct-worker.conf"
else
    echo "  Configuration already exists, skipping"
fi

# Install systemd service
echo "Installing systemd service..."
cp "$SCRIPT_DIR/macct-worker.service" /etc/systemd/system/macct-worker.service
systemctl daemon-reload

# Enable and start service
echo "Enabling service..."
systemctl enable macct-worker

echo ""
echo "=========================================="
echo "Installation complete!"
echo "=========================================="
echo ""
echo "Configuration: /etc/macct-worker.conf"
echo "Log directory: /var/log/macct"
echo "Service:       macct-worker.service"
echo ""
echo "Commands:"
echo "  Start:   systemctl start macct-worker"
echo "  Stop:    systemctl stop macct-worker"
echo "  Status:  systemctl status macct-worker"
echo "  Logs:    journalctl -u macct-worker -f"
echo ""
echo "Before starting, verify:"
echo "  1. Redis is accessible: redis-cli -h $LINBO_DOCKER_IP ping"
echo "  2. API is accessible:   curl http://$LINBO_DOCKER_IP:3000/health"
echo "  3. Configuration is correct: cat /etc/macct-worker.conf"
echo ""
echo "To start the worker:"
echo "  systemctl start macct-worker"
echo ""
